package com.rt.indexing.persistence

import com.rt.util.NameMapper


/**
 * Contains ALL the data about an album including file info
 * TODO use the ID (autogenerated, not based on name) as the album file name
 */
class Album(val id:String, val fileInfo:AlbumFile, val metaData:AlbumMetaData){
  def this(metaData:AlbumMetaData) = this(NameMapper.nUnder(metaData.title), new AlbumFile(metaData.title), metaData)

  override def toString():String={
    "Album[metadata="+metaData+", fileInfo="+fileInfo+"]"
  }
}
